name: Thunderstore Bundle

on:
  workflow_dispatch:
    branches: [master]

jobs:
  build:
    runs-on: dsp-installed

    env:
      Solution_Name: Nebula.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 # can't shallowly clone due to git versioning

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: 'npm'
      - run: npm install @terascope/fetch-github-release
      - run: npm install json2toml
      - run: npm install xml-reader
      - run: npm install xml-query
      - run: npm install zip-a-folder

      - name: Clear output directory in DSP files
        # We use SilentlyContinue here because it errors out if the folder does not exist otherwise
        run: rm -R -ErrorAction SilentlyContinue "C:\Program Files (x86)\Steam\steamapps\common\Dyson Sphere Program\BepInEx\plugins\Nebula"

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      # Build it
      - name: Build the application
        run: msbuild $env:Solution_Name /p:Configuration=Release

      # Bundle
      - name: Bundle build for thunderstore
        env:
          TSTORE_TOKEN: ${{ secrets.TSTORE_TOKEN }}
        run: node .github\scripts\thunderstore_bundle.js

      # Upload it to the run results
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: nebula-thunderstore
          path: dist\thunderstore\nebula
